/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Contabilidad.Beneficiario;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MARIAJOSE
 */
public class AnadirTerceroPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnadirTerceroPanel
     */
    public AnadirTerceroPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ingresar1 = new javax.swing.JTextField();
        ingresar2 = new javax.swing.JTextField();
        ingresar3 = new javax.swing.JTextField();
        ingresar4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setText("Añadir tercero");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 74, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Completo:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 151, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Cédula/NIT:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 151, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Dirección:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 151, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Teléfono:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 151, -1, -1));

        ingresar1.setText("Ingrese nombre");
        ingresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar1ActionPerformed(evt);
            }
        });
        add(ingresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 179, 130, 30));

        ingresar2.setText("Ingrese cédula");
        ingresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar2ActionPerformed(evt);
            }
        });
        add(ingresar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 179, 124, 30));

        ingresar3.setText("Ingrese dirección");
        ingresar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar3ActionPerformed(evt);
            }
        });
        add(ingresar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 179, 124, 30));

        ingresar4.setText("Ingrese teléfono");
        ingresar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar4ActionPerformed(evt);
            }
        });
        add(ingresar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 179, 124, 30));

        jButton2.setText("Atrás");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(642, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 780, 190));
    }// </editor-fold>//GEN-END:initComponents

    private void ingresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar1ActionPerformed
      ingresar1.getSelectedText();  // TODO add your handling code here:
    }//GEN-LAST:event_ingresar1ActionPerformed

    private void ingresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar2ActionPerformed
        ingresar2.getText();
    }//GEN-LAST:event_ingresar2ActionPerformed

    private void ingresar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ingresar3ActionPerformed

    private void ingresar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresar4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String  hi =ingresar1.getText();
String hi2 = ingresar2.getText();
String hi3 = ingresar3.getText();
String hi4 = ingresar4.getText();
Beneficiario uno = new Beneficiario (hi, hi2, hi3, hi4);
                           File beneficiarios = new File ("Beneficiarios/beneficiarios.txt");
                        
                      //    BufferedWriter  bw = "";
                      BufferedWriter bw = null;
        try {
           bw = new BufferedWriter(new FileWriter(beneficiarios,true));
        } catch (IOException ex) {
            Logger.getLogger(AnadirTerceroPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
                            String cadena = uno.getNombreTercero()+"," +uno.getCedulaNit()+","+  uno.getDireccion() + "," + uno.getTelefono();
        try {
            bw.newLine();
        } catch (IOException ex) {
            Logger.getLogger(AnadirTerceroPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
                            
        try {
            bw.write(cadena);
        } catch (IOException ex) {
            Logger.getLogger(AnadirTerceroPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            bw.close();
            JOptionPane.showMessageDialog(null, uno.getNombreTercero() +" se ha añadido");
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(AnadirTerceroPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ingresar1;
    private javax.swing.JTextField ingresar2;
    private javax.swing.JTextField ingresar3;
    private javax.swing.JTextField ingresar4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
