/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintStream;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import wabisabinomina.Empresa;
import wabisabinomina.WabiSabiNomina;

/**
 *
 * @author Maicol Velasquez
 */
public class CambiarD extends javax.swing.JFrame {

    
    Empresa empresa = new Empresa();
File archiFecha = new File("Empresa/FechaNomina.txt");
 File archiTrab = new File("Empresa/Trabajadores.txt");
        File Directorio = new File("Empresa");
        File archiEmpr = new File("Empresa/Datos Empresa.txt");
        File archiCont = new File("Empresa/Contratos.txt");

    /**
     * Creates new form CambiarD
     */
    public CambiarD() {
        this.setExtendedState(MAXIMIZED_BOTH);
      Scanner de = new Scanner (System.in);
       new WabiSabiNomina().leerContras(archiCont, empresa);
        new WabiSabiNomina().leerTrabs(archiTrab, empresa);
         new WabiSabiNomina().iniciar(empresa, archiEmpr, de);
       
        // this.setLocationRelativeTo(this);
        setIconImage(new ImageIcon(getClass().getResource("/interfaz/imagenes/logows1.png")).getImage());

            
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupContribuy = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelU = new javax.swing.JLabel();
        jLabelNob = new javax.swing.JLabel();
        jLabelU1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelU2 = new javax.swing.JLabel();
        jLabelU3 = new javax.swing.JLabel();
        jLabelU4 = new javax.swing.JLabel();
        jTextFieldNombre5 = new javax.swing.JTextField();
        jTextFieldNombre6 = new javax.swing.JTextField();
        jTextFieldNombre7 = new javax.swing.JTextField();
        jTextFieldNombre8 = new javax.swing.JTextField();
        jTextFieldNombre9 = new javax.swing.JTextField();
        jTextFieldNombre10 = new javax.swing.JTextField();
        jLabelU5 = new javax.swing.JLabel();
        jLabelU6 = new javax.swing.JLabel();
        jLabelU7 = new javax.swing.JLabel();
        jLabelU8 = new javax.swing.JLabel();
        jTextFieldNombre11 = new javax.swing.JTextField();
        jTextFieldNombre13 = new javax.swing.JTextField();
        jTextFieldNombre14 = new javax.swing.JTextField();
        jLabelU10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButtonVer = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonCerrarS = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabelContra1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelContra = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ModificarDatos - WabiSabi");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setToolTipText("MoficarDatos - WabiSabi");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelU.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelU.setText("Moneda que maneja:");
        jPanel1.add(jLabelU, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, -1, -1));

        jLabelNob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNob.setText("Nombre empresa:");
        jPanel1.add(jLabelNob, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 130, -1));

        jLabelU1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelU1.setText(">> Modificar ");
        jPanel1.add(jLabelU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("GUARDAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 610, 120, 40));

        jLabelU2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelU2.setText("Representante Legal:");
        jPanel1.add(jLabelU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 200, -1, -1));

        jLabelU3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelU3.setText("Nit: ");
        jPanel1.add(jLabelU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        jLabelU4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelU4.setText("Dirección: ");
        jPanel1.add(jLabelU4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 260, -1, -1));

        jTextFieldNombre5.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldNombre5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 210, 30));

        jTextFieldNombre6.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldNombre6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldNombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 210, 30));

        jTextFieldNombre7.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldNombre7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldNombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 140, 210, 30));

        jTextFieldNombre8.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldNombre8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldNombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 210, 30));

        jTextFieldNombre9.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldNombre9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldNombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 200, 210, 30));

        jTextFieldNombre10.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldNombre10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldNombre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 210, 30));

        jLabelU5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelU5.setText("Teléfono:");
        jPanel1.add(jLabelU5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        jLabelU6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelU6.setText("Número de empleados :");
        jPanel1.add(jLabelU6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 420, -1, -1));

        jLabelU7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelU7.setText("Es Gran Contribuyente:");
        jPanel1.add(jLabelU7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, -1, -1));

        jLabelU8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelU8.setText("Régimen Legal :");
        jPanel1.add(jLabelU8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));

        jTextFieldNombre11.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldNombre11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldNombre11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 260, 210, 30));

        jTextFieldNombre13.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldNombre13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldNombre13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 210, 30));

        jTextFieldNombre14.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldNombre14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldNombre14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 210, 30));

        jLabelU10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelU10.setText("Usuario: ");
        jPanel1.add(jLabelU10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(204, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 330, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonVer.setBackground(new java.awt.Color(0, 204, 255));
        jButtonVer.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButtonVer.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/verNo.png"))); // NOI18N
        jButtonVer.setText("Ver Datos");
        jButtonVer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonVer.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/verNo2.png"))); // NOI18N
        jButtonVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVerMouseClicked(evt);
            }
        });
        jPanel2.add(jButtonVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 240, -1));

        jButtonEditar.setBackground(new java.awt.Color(0, 204, 255));
        jButtonEditar.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/editar.png"))); // NOI18N
        jButtonEditar.setText("Editar Datos");
        jButtonEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/editar2.png"))); // NOI18N
        jButtonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditarMouseClicked(evt);
            }
        });
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 240, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/portal.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jButtonCerrarS.setBackground(new java.awt.Color(0, 204, 255));
        jButtonCerrarS.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButtonCerrarS.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCerrarS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/cerrarSesion.png"))); // NOI18N
        jButtonCerrarS.setText("   Cerra Sesión");
        jButtonCerrarS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonCerrarS.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonCerrarS.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/cerrarSesion2.png"))); // NOI18N
        jButtonCerrarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCerrarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 240, -1));

        jButtonRegresar.setBackground(new java.awt.Color(0, 204, 255));
        jButtonRegresar.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/atras.png"))); // NOI18N
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonRegresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/atras2.png"))); // NOI18N
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 240, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 770));

        jLabelContra1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelContra1.setText("Contraseña:");
        jPanel1.add(jLabelContra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, 90, 20));

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelContra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelContra.setText("Datos Empresa:");
        jPanel3.add(jLabelContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 410, 50));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 410, 410));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldNombre.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel5.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 110, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 450, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditarMouseClicked

        
        jComboBox1.setVisible(true);
        
     jTextFieldNombre6.setText(empresa.getUsuario());
     jTextFieldNombre6.setEditable(true);
       jTextFieldNombre8.setText(empresa.getNombre());
       jTextFieldNombre8.setEditable(true);
       jTextFieldNombre10.setText(empresa.getNit());
       jTextFieldNombre10.setEditable(true);
       jTextFieldNombre13.setText(empresa.getTel());
        jTextFieldNombre13.setEditable(true);
        jTextFieldNombre14.setText(empresa.getRgimen());
         jTextFieldNombre14.setEditable(true);
         jTextFieldNombre5.setText(empresa.getMoneda());
          jTextFieldNombre5.setEditable(true);
        jTextFieldNombre7.setText(empresa.getContraseña());
        jTextFieldNombre7.setEditable(true);
         jTextFieldNombre9.setText(empresa.getRlegal());
         jTextFieldNombre9.setEditable(true);
          jTextFieldNombre11.setText(empresa.getDir());
          jTextFieldNombre11.setEditable(true);
           jTextFieldNombre.setText((String.valueOf(empresa.getTras().size())));
           jTextFieldNombre.setEditable(true); 
     
    }//GEN-LAST:event_jButtonEditarMouseClicked

    private void jButtonVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVerMouseClicked

        
        jComboBox1.setVisible(false);
        
        
  jTextFieldNombre6.setText(empresa.getUsuario());
     jTextFieldNombre6.setEditable(false);
       jTextFieldNombre8.setText(empresa.getNombre());
       jTextFieldNombre8.setEditable(false);
       jTextFieldNombre10.setText(empresa.getNit());
       jTextFieldNombre10.setEditable(false);
       jTextFieldNombre13.setText(empresa.getTel());
        jTextFieldNombre13.setEditable(false);
        jTextFieldNombre14.setText(empresa.getRgimen());
         jTextFieldNombre14.setEditable(false);
         jTextFieldNombre5.setText(empresa.getMoneda());
          jTextFieldNombre5.setEditable(false);
        jTextFieldNombre7.setText(empresa.getContraseña());
        jTextFieldNombre7.setEditable(false);
         jTextFieldNombre9.setText(empresa.getRlegal());
         jTextFieldNombre9.setEditable(false);
          jTextFieldNombre11.setText(empresa.getDir());
          jTextFieldNombre11.setEditable(false);
           jTextFieldNombre.setText((String.valueOf(empresa.getTras().size())));
           jTextFieldNombre.setEditable(false);
        
        
        


    }//GEN-LAST:event_jButtonVerMouseClicked

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

 PrintStream Out1;
        try {
            Out1 = new PrintStream(archiEmpr);
       
                    int cosito = 1;
                    Out1.print(cosito + "\n");

//                    System.out.println("Usuario:");
//                    empresa.setUsuario(en.nextLine());
                    Out1.print(jTextFieldNombre6.getText() + "\n");
//                    System.out.println("contraseña:");
//                    empresa.setContraseña(en.nextLine() + "\n");
                    Out1.print(jTextFieldNombre7.getText ()+ "\n");
//                    System.out.println("Nombre:\n");
//                    empresa.setNombre(en.nextLine());
                    Out1.print( jTextFieldNombre8.getText() + "\n");

//                    System.out.println("Representante legal:\n");
//                    empresa.setRlegal(en.nextLine());
                    Out1.print(jTextFieldNombre9.getText() + "\n");
//                    System.out.println("Nit de la empresa: \n");
//                    empresa.setNit(en.nextLine());
                    Out1.print( jTextFieldNombre10.getText() + "\n");
                    System.out.println("Direcion de la empresa:\n");
//                    empresa.setDir(en.nextLine());
                    Out1.print( jTextFieldNombre11.getText() + "\n");
                    System.out.println("Telefono :\n");
//                    empresa.setTel(en.nextLine());
                    Out1.print( jTextFieldNombre13.getText() + "\n");
                    System.out.println("Regimen legal: \n");
//                    empresa.setRgimen(en.nextLine());
                    Out1.print(jTextFieldNombre14.getText() + "\n");
                    System.out.println("Es gran contribuyente (SI o NO): /n");
//                    String cont = en.nextLine();
                    if (( jComboBox1.getSelectedItem().equals("SI"))){
                          empresa.setGranCont(true);
                    }else {
                        empresa.setGranCont(false);
                    }

  
                    Out1.print(empresa.isGranCont() + "\n");
                    System.out.println("moneda que maneja: \n");
                 //   empresa.setMoneda(en.nextLine());
                    Out1.print(jTextFieldNombre5.getText() + "\n");
                    System.out.println("Numero de empleados:");
                   // int Nemple = en.nextInt();
                    //en.nextLine();
                    String TipApor = empresa.tipoAportador(empresa.getTras().size());
                    Out1.print(TipApor + "\n");
                 

 } catch (FileNotFoundException ex) {
            Logger.getLogger(CambiarD.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1MouseClicked

    private void jButtonCerrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSActionPerformed

        interfaz a = new interfaz() ;
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCerrarSActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed

        MenuPrincipal a = new MenuPrincipal();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new CambiarD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupContribuy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCerrarS;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelContra;
    private javax.swing.JLabel jLabelContra1;
    private javax.swing.JLabel jLabelNob;
    private javax.swing.JLabel jLabelU;
    private javax.swing.JLabel jLabelU1;
    private javax.swing.JLabel jLabelU10;
    private javax.swing.JLabel jLabelU2;
    private javax.swing.JLabel jLabelU3;
    private javax.swing.JLabel jLabelU4;
    private javax.swing.JLabel jLabelU5;
    private javax.swing.JLabel jLabelU6;
    private javax.swing.JLabel jLabelU7;
    private javax.swing.JLabel jLabelU8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombre10;
    private javax.swing.JTextField jTextFieldNombre11;
    private javax.swing.JTextField jTextFieldNombre13;
    private javax.swing.JTextField jTextFieldNombre14;
    private javax.swing.JTextField jTextFieldNombre5;
    private javax.swing.JTextField jTextFieldNombre6;
    private javax.swing.JTextField jTextFieldNombre7;
    private javax.swing.JTextField jTextFieldNombre8;
    private javax.swing.JTextField jTextFieldNombre9;
    // End of variables declaration//GEN-END:variables
}
