/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author MARIAJOSE
 */
public class ContPrincipal extends javax.swing.JFrame {
TercerosOp panelTer = new TercerosOp();
CuentasOp panelCu = new CuentasOp();
    /**
     * Creates new form Tabla1
     */
    public ContPrincipal() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Selec = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelFondo = new javax.swing.JPanel();
        PanelElegir1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Terceros = new javax.swing.JRadioButton();
        Estados = new javax.swing.JRadioButton();
        Cuentas = new javax.swing.JRadioButton();
        Entrada = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));

        PanelFondo.setBackground(new java.awt.Color(102, 153, 255));

        PanelElegir1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 153, 255));
        jLabel4.setText("Contabilidad");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/icoConta/icono1.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/icoConta/menuIni/terceros1.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/icoConta/menuIni/Cuentas1.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/icoConta/menuIni/movimientos1.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/icoConta/menuIni/estados1.png"))); // NOI18N

        Terceros.setBackground(new java.awt.Color(51, 102, 255));
        Selec.add(Terceros);
        Terceros.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Terceros.setText("TERCEROS");
        Terceros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TercerosActionPerformed(evt);
            }
        });

        Estados.setBackground(new java.awt.Color(51, 102, 255));
        Selec.add(Estados);
        Estados.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Estados.setText("ESTADOS FINANCIEROS\n");
        Estados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadosActionPerformed(evt);
            }
        });

        Cuentas.setBackground(new java.awt.Color(51, 102, 255));
        Selec.add(Cuentas);
        Cuentas.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Cuentas.setText("CUENTAS");
        Cuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentasActionPerformed(evt);
            }
        });

        Entrada.setBackground(new java.awt.Color(51, 102, 255));
        Selec.add(Entrada);
        Entrada.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Entrada.setText("ENTRADA DE DOCUMENTOS\n");
        Entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jButton2.setText("Seleccionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelElegir1Layout = new javax.swing.GroupLayout(PanelElegir1);
        PanelElegir1.setLayout(PanelElegir1Layout);
        PanelElegir1Layout.setHorizontalGroup(
            PanelElegir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelElegir1Layout.createSequentialGroup()
                .addGroup(PanelElegir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelElegir1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(PanelElegir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(PanelElegir1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Estados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelElegir1Layout.createSequentialGroup()
                .addGroup(PanelElegir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelElegir1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(PanelElegir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelElegir1Layout.createSequentialGroup()
                                .addComponent(Entrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8))
                            .addGroup(PanelElegir1Layout.createSequentialGroup()
                                .addComponent(Terceros, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6))
                            .addGroup(PanelElegir1Layout.createSequentialGroup()
                                .addComponent(Cuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)))
                        .addGap(0, 170, Short.MAX_VALUE))
                    .addGroup(PanelElegir1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(19, 19, 19))
        );
        PanelElegir1Layout.setVerticalGroup(
            PanelElegir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelElegir1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(54, 54, 54)
                .addGroup(PanelElegir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Terceros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(49, 49, 49)
                .addGroup(PanelElegir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Cuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(PanelElegir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(PanelElegir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Estados, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addComponent(PanelElegir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1057, Short.MAX_VALUE))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelElegir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TercerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TercerosActionPerformed
       
    }//GEN-LAST:event_TercerosActionPerformed

    private void EntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaActionPerformed

    private void CuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentasActionPerformed

    private void EstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Selec.add(Terceros);
        Selec.add(Estados);
        Selec.add(Cuentas);
        Selec.add(Entrada);
        if (Terceros.isSelected()){
            
            TercerosOp panerTer = new TercerosOp ();
        panerTer.setSize(700, 500);
        panerTer.setLocation(500, 100);
        PanelFondo.add(panerTer, BorderLayout.CENTER);
        PanelFondo.revalidate();
        PanelFondo.repaint();
  

        
        } else if (Entrada.isSelected()){
             EntradaOp ent1= new EntradaOp();
        ent1.setSize(700, 500);
        ent1.setLocation(500, 100);
        PanelFondo.add(ent1, BorderLayout.CENTER);
        PanelFondo.revalidate();
        PanelFondo.repaint();
        
        
        } else if (Cuentas.isSelected()){
           CuentasOp panerCu = new CuentasOp ();
        panerCu.setSize(700, 500);
        panerCu.setLocation(500, 100);
        PanelFondo.add(panerCu, BorderLayout.CENTER);
        PanelFondo.revalidate();
        PanelFondo.repaint();
        }else if (Estados.isSelected()){
            GenerarOp genCu = new GenerarOp ();
        genCu.setSize(700, 500);
        genCu.setLocation(500, 100);
        PanelFondo.add(genCu, BorderLayout.CENTER);
        PanelFondo.revalidate();
        PanelFondo.repaint();
        } else {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado función");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContPrincipal().setVisible(true);
            }
        });
    }
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cuentas;
    private javax.swing.JRadioButton Entrada;
    private javax.swing.JRadioButton Estados;
    public static javax.swing.JPanel PanelElegir1;
    public static javax.swing.JPanel PanelFondo;
    private javax.swing.ButtonGroup Selec;
    private javax.swing.JRadioButton Terceros;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
