/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import interfaz.MostrarC;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author MARIAJOSE
 */
public class CuentasOp extends javax.swing.JPanel {

    /**
     * Creates new form MovimientosOp
     */
    public CuentasOp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        VerCuentas = new javax.swing.JRadioButton();
        AcepC = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 255));
        setAutoscrolls(true);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/icoConta/menuIni/Cuentas.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 77, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setText("Cuentas");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 288, -1, -1));

        VerCuentas.setBackground(new java.awt.Color(0, 0, 102));
        VerCuentas.setFont(new java.awt.Font("Times New Roman", 2, 30)); // NOI18N
        VerCuentas.setSelected(true);
        VerCuentas.setText("Ver cuentas");
        add(VerCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 201, -1, -1));

        AcepC.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        AcepC.setText("Aceptar");
        AcepC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcepCActionPerformed(evt);
            }
        });
        add(AcepC, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 359, -1, -1));

        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 436, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AcepCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcepCActionPerformed
        // TODO add your handling code here:
        if (VerCuentas.isSelected()){
            try {
                MostrarC.createAndShowGUIBEN();
            } catch (IOException ex) {
                Logger.getLogger(CuentasOp.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_AcepCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcepC;
    private javax.swing.JRadioButton VerCuentas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
