/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Contabilidad.RegistroDia;
import java.io.File;
import java.util.ArrayList;
import Contabilidad.Beneficiario;
import Contabilidad.Cat1;
import Contabilidad.Clase;
import Contabilidad.Contabilidad;
import Contabilidad.Cuenta;
import Contabilidad.Registro1;
import Contabilidad.RegistroDia;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author MARIAJOSE
 */
public class Entrada extends javax.swing.JPanel {
        Object  [][]data = new Object[100][100];
        String[]cabecera = {"Cuenta", "Descripcion", "Tercero","Monto"}; 
        int contador =0;
        RegistroDia q;
    /**
     * Creates new form NewJPanel
     */
    public Entrada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        diaC = new javax.swing.JTextField();
        numCom = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        mesC = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ShowUsu = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        ShowEmpresa = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        text2 = new javax.swing.JTextField();
        text1 = new javax.swing.JTextField();
        text3 = new javax.swing.JTextField();
        text4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Número de comprobante:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 130, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Empresa: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 65, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Usuario:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 65, -1));

        diaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaCActionPerformed(evt);
            }
        });
        jPanel1.add(diaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 30, -1));
        jPanel1.add(numCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 30, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Fecha:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 65, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 40, -1));

        mesC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febbrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        mesC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesCActionPerformed(evt);
            }
        });
        jPanel1.add(mesC, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("año");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("día");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("mes");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jScrollPane4.setViewportView(ShowUsu);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 80, -1));

        jScrollPane5.setViewportView(ShowEmpresa);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 80, -1));

        jButton2.setText("Iniciar registro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 24, 750, 110));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cuenta", "Tercero", "Descripción", "Monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 750, 90));

        text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text2ActionPerformed(evt);
            }
        });

        text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1ActionPerformed(evt);
            }
        });

        text3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text3ActionPerformed(evt);
            }
        });

        text4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text4ActionPerformed(evt);
            }
        });

        jLabel4.setText("Debito");

        jLabel8.setText("Debito");

        jScrollPane2.setViewportView(jTextPane1);

        jScrollPane3.setViewportView(jTextPane2);

        jButton1.setText("Añadir registro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(4, 4, 4)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 750, 140));
    }// </editor-fold>//GEN-END:initComponents
 
    private void text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text2ActionPerformed

    private void text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text1ActionPerformed

    private void text3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text3ActionPerformed

    private void text4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          Cat1 catalogoCuentas = new Cat1 ();
      Contabilidad cont1 = new Contabilidad(catalogoCuentas);
      File clases = new File ("cuentas/clase.txt");
      
      //crear clases
       FileReader leeClase = null;
            try {
                leeClase = new FileReader (clases);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
            }
      BufferedReader bc1 = new BufferedReader  (leeClase);
      String lineaClase;
      Clase[] clase = new Clase[6];
       int j = 0;
            try {
                while ( (lineaClase = bc1.readLine()) != null && j<=5){
                    
                    String div[] = lineaClase.split(",");
                    int numero1 = Integer.parseInt(div[0]);
                    String nombreCuenta = div[1];
                    String naturalezaCuenta = div[2];
                    Clase clases1 = new Clase (numero1, nombreCuenta,naturalezaCuenta);
                    
                    clase[j] = clases1;
                    
                    
                    
                    j++;
                }     } catch (IOException ex) {
                Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
            }
      
     // crear catalogo clases
//     String nomArc []= {"activos", "pasivos", "patrimonio", "ingresos","gastos" , "costosdeventa", "costosdePuO"};
//      
//     for (int i=0; i< nomArc.length; i++){
         File cuentas = new File ("cuentas/activos.txt");
         FileReader leeCuenta = null;
            try {
                leeCuenta = new FileReader (cuentas);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
            }
      BufferedReader bc2 = new BufferedReader  (leeCuenta);
      String lineaCuenta;
            try {
                while ( (lineaCuenta = bc2.readLine()) != null){
                    
                    //  int k=0;
                    String divCuenta[] = lineaCuenta.split(",");
                    
                    String hello ="";
                    String hello1 ="";
                    for (int k=0; k<6; k++) {
                        String hy = divCuenta[0];
                        clase[k].getNombreClase();
                        
                        if (hy.equals(clase[k].getNombreClase())){
                            j = clase[k].getNumero();
                            hello = clase[k].getNombreClase();
                            hello1 = clase [k].getNaturaleza();
                            
                            Clase clase11 = new Clase (j, hello, hello1);
                            int numeCuenta = Integer.parseInt(divCuenta[1]);
                            String num1 = divCuenta[1];
                            String grupoCuenta = divCuenta[2];
                            String num2 = divCuenta[3];
                            int numCuenta = Integer.parseInt(divCuenta[3]);
                            String cuentaC = divCuenta[4];
                            String num3 = divCuenta [5];
                            int numSubCuenta = Integer.parseInt(divCuenta[5]);
                            String nomSubCuenta = divCuenta[6];
                            String ls = Integer.toString(j) +num1 +num2 +num3;
                            
                            Cuenta crearcuentas = new Cuenta (clase11, numeCuenta , grupoCuenta, numCuenta,cuentaC, numSubCuenta, nomSubCuenta, ls);
                            catalogoCuentas.addCuenta1(crearcuentas);
                        } else{
                            
                        }
                    };
                    
                }    } catch (IOException ex) {
                Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
            }
        String cuenta = text1.getText();
        int b = 0;
        String nat = "";
        String nombre = "";
        int numGrupo = 0;
        String grupo = "";
        int numCuentaa = 0; 
        String cuenta1 = "";
          int numSub = 0;
         String subcuenta = "";
         String nc = "";
        for (Cuenta c1 : catalogoCuentas.getCuentas()){
            if (cuenta.equals(c1.getNumeroCuenta())){
                b = c1.getClase().getNumero(); nombre = c1.getClase().getNombreClase(); nat = c1.getClase().getNaturaleza();
                numGrupo = c1.getNumGrupo(); grupo = c1.getGrupo(); numCuentaa = c1.getNumCuentaa(); cuenta1 = c1.getCuenta();
                numSub =  c1.getNumSub(); subcuenta = c1.getSubcuenta(); nc = c1.getNumeroCuenta();
            }
        } 
        Clase x = new Clase (b,nombre, nat );
        Cuenta v = new Cuenta (x, numGrupo, grupo, numCuentaa, cuenta1, numSub, subcuenta, nc);
       String bene = text2.getText();
       String descripcion  = text3.getText();
       String monto = text4.getText();
       Double monto1 = Double.parseDouble(text4.getText());
       ArrayList<Object[]> arr = new ArrayList<>();
       Object[] temp = {cuenta, bene, descripcion, monto};
       data[contador] = temp;
       contador++;
       jTable1.setModel(new javax.swing.table.DefaultTableModel(data, cabecera));
       jTable1.repaint();
       
       
      // Registro1 registro = Registro1(x, );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void diaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaCActionPerformed
      String dia1 =diaC.getText();
      int dia = Integer.parseInt(dia1);
      String mes = mesC.getActionCommand();
      File file = new File (mes +"/" + dia +".txt");
    }//GEN-LAST:event_diaCActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTable1.setVisible(true);
        jPanel2.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mesCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesCActionPerformed
      String anio1 = jTextField3.getText();
        String mes1 = mesC.getActionCommand();
       File folder = new File ("Registros/"+anio1+"/" + mes1);
       folder.mkdir();
    }//GEN-LAST:event_mesCActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
       File folder1 = new File ("Registros/" + jTextField3.getText());
    }//GEN-LAST:event_jTextField3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane ShowEmpresa;
    private javax.swing.JTextPane ShowUsu;
    private javax.swing.JTextField diaC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JComboBox<String> mesC;
    private javax.swing.JTextField numCom;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text4;
    // End of variables declaration//GEN-END:variables
}
