/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import static interfaz.ContPrincipal.PanelFondo;
import java.awt.BorderLayout;
import Contabilidad.Registro1;
import Contabilidad.RegistroDia;
import Contabilidad.RegistroMes;

/**
 *
 * @author MARIAJOSE
 */
public class EntradaOp extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public EntradaOp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hola22 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 255));
        setInheritsPopupMenu(true);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/icoConta/menuIni/movimientos.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 49, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setText("Entrada de documentos");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 268, -1, -1));

        hola22.setBackground(new java.awt.Color(0, 0, 102));
        buttonGroup3.add(hola22);
        hola22.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        hola22.setText("Crear registro diario");
        hola22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hola22ActionPerformed(evt);
            }
        });
        add(hola22, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 172, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        jButton2.setText("Atrás");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void hola22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hola22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hola22ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
        if (hola22.isSelected()){
           Entrada en1= new Entrada();
        en1.setSize(800, 600);
        en1.setLocation(500, 100);
        PanelFondo.add(en1, BorderLayout.CENTER);
        PanelFondo.revalidate();
        PanelFondo.repaint();
       }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton hola22;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
