//package Interfaz;
//
//import javax.swing.ImageIcon;
//
//
///**
// *
// * @author Maicol Velasquez
// */
//public class Interfaz extends javax.swing.JFrame {
//
//    /**
//     * Creates new form interfaz
//     */
//    public Interfaz() {
//        initComponents();
//        setIconImage(new ImageIcon(getClass().getResource("/interfaz/imagenes/icono.png")).getImage());       
//    }
//    
//     
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//    private void initComponents() {
//        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();
//
//        jBUSalir1 = new javax.swing.JButton();
//        jLabelIconoUsuario = new javax.swing.JLabel();
//        jLabelUsu = new javax.swing.JLabel();
//        jLabelContras = new javax.swing.JLabel();
//        jPasswordFieldContra = new javax.swing.JPasswordField();
//        jTextFieldUsu = new javax.swing.JTextField();
//        jButtonIniciarS = new javax.swing.JButton();
//        jComboBox1 = new javax.swing.JComboBox<>();
//        jTextField1 = new javax.swing.JTextField();
//        jLabelFondo = new javax.swing.JLabel();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
//
//        jBUSalir1.setBackground(new java.awt.Color(0, 102, 204));
//        jBUSalir1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
//        jBUSalir1.setForeground(new java.awt.Color(255, 255, 255));
//        jBUSalir1.setText("Salir");
//        jBUSalir1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jBUSalir1ActionPerformed(evt);
//            }
//        });
//        getContentPane().add(jBUSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 80, 30));
//
//        jLabelIconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/personal.png"))); // NOI18N
//        getContentPane().add(jLabelIconoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 260, 440));
//
//        jLabelUsu.setBackground(new java.awt.Color(255, 255, 255));
//        jLabelUsu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
//        jLabelUsu.setForeground(new java.awt.Color(255, 255, 255));
//        jLabelUsu.setText("Usuario:");
//        getContentPane().add(jLabelUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, -1, -1));
//
//        jLabelContras.setBackground(new java.awt.Color(255, 255, 255));
//        jLabelContras.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
//        jLabelContras.setForeground(new java.awt.Color(255, 255, 255));
//        jLabelContras.setText("Contraseña:");
//        getContentPane().add(jLabelContras, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 140, 20));
//
//        jPasswordFieldContra.setBackground(new java.awt.Color(0, 51, 204));
//        jPasswordFieldContra.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
//        jPasswordFieldContra.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jPasswordFieldContraActionPerformed(evt);
//            }
//        });
//        getContentPane().add(jPasswordFieldContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 200, 30));
//
//        jTextFieldUsu.setBackground(new java.awt.Color(0, 51, 204));
//        jTextFieldUsu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
//        jTextFieldUsu.setForeground(new java.awt.Color(255, 255, 255));
//        getContentPane().add(jTextFieldUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 200, 30));
//
//        jButtonIniciarS.setBackground(new java.awt.Color(0, 51, 204));
//        jButtonIniciarS.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
//        jButtonIniciarS.setForeground(new java.awt.Color(255, 255, 255));
//        jButtonIniciarS.setText("Iniciar Sesión");
//        jButtonIniciarS.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                jButtonIniciarSMouseClicked(evt);
//            }
//        });
//        jButtonIniciarS.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButtonIniciarSActionPerformed(evt);
//            }
//        });
//        getContentPane().add(jButtonIniciarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 630, -1, -1));
//
//        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
//        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));
//
//        jTextField1.setText("jTextField1");
//        jTextField1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextField1ActionPerformed(evt);
//            }
//        });
//        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));
//
//        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("jdf"), jLabelFondo, org.jdesktop.beansbinding.BeanProperty.create("text"));
//        bindingGroup.addBinding(binding);
//
//        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 0, -1, -1));
//
//        bindingGroup.bind();
//
//        pack();
//    }// </editor-fold>                        
//
//    private void jBUSalir1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
//                 System.exit(0);
//    }                                         
//
//   
//    
//    private void jPasswordFieldContraActionPerformed(java.awt.event.ActionEvent evt) {                                                     
//        // TODO add your handling code here:
//    }                                                    
//
//    private void jButtonIniciarSActionPerformed(java.awt.event.ActionEvent evt) {                                                
//        // TODO add your handling code here:
//    }                                               
//
//    private void jButtonIniciarSMouseClicked(java.awt.event.MouseEvent evt) {                                             
//        String str = jLabelUsu.getText();
//        if( true ) {
//            jpanel newPanel = new jpanel(usuario, contra);
//            jpanel.setVisible(true);
//            this.setVisible(false);
//        }
//    }                                            
//
//    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
//        // TODO add your handling code here:
//    }                                           
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//               // Image icon = getIconImage;
//               String str = jLabelUsu.getText();
//                new interfaz().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify                     
//    private javax.swing.JButton jBUSalir1;
//    private javax.swing.JButton jButtonIniciarS;
//    private javax.swing.JComboBox<String> jComboBox1;
//    private javax.swing.JLabel jLabelContras;
//    private javax.swing.JLabel jLabelFondo;
//    private javax.swing.JLabel jLabelIconoUsuario;
//    private javax.swing.JLabel jLabelUsu;
//    private javax.swing.JPasswordField jPasswordFieldContra;
//    private javax.swing.JTextField jTextField1;
//    private javax.swing.JTextField jTextFieldUsu;
//    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
//    // End of variables declaration                   
//}
//
