/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import static interfaz.ContPrincipal.PanelFondo;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;

/**
 *
 * @author Maicol Velasquez
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        //this.setLocationRelativeTo(this);
        this.setExtendedState(MAXIMIZED_BOTH);
                setIconImage(new ImageIcon(getClass().getResource("/interfaz/imagenes/logows1.png")).getImage());       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNomina = new javax.swing.JButton();
        jButtonContabi1 = new javax.swing.JButton();
        jButtonInven1 = new javax.swing.JButton();
        jPanelMenu = new javax.swing.JPanel();
        jLabelPortal = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonCerrarS = new javax.swing.JButton();
        jButtonEditarD = new javax.swing.JButton();
        jLabelNombrePag = new javax.swing.JLabel();
        jButtonMenu1 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MenuPrincipal - WabiSabiContabilidad");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNomina.setBackground(new java.awt.Color(0, 0, 255));
        jButtonNomina.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButtonNomina.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNomina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/icoNomi/INomina1.png"))); // NOI18N
        jButtonNomina.setText("NOMINA");
        jButtonNomina.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNomina.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/icoNomi/INomina2.png"))); // NOI18N
        jButtonNomina.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/icoNomi/INomina.png"))); // NOI18N
        jButtonNomina.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNominaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 320, 280));

        jButtonContabi1.setBackground(new java.awt.Color(0, 0, 255));
        jButtonContabi1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButtonContabi1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonContabi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/icoConta/icono1.png"))); // NOI18N
        jButtonContabi1.setText("CONTABILIDAD");
        jButtonContabi1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonContabi1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/icoConta/icono2.png"))); // NOI18N
        jButtonContabi1.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Maicol Velasquez\\Documents\\NetBeansProjects\\WabiSabiNomina\\src\\interfaz\\imagenes\\icoConta\\icono.png")); // NOI18N
        jButtonContabi1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonContabi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContabi1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonContabi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 320, 280));

        jButtonInven1.setBackground(new java.awt.Color(0, 0, 255));
        jButtonInven1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButtonInven1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInven1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/IcoInven/Inventario2.png"))); // NOI18N
        jButtonInven1.setText("INVENTARIO");
        jButtonInven1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonInven1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/IcoInven/Inventario3.png"))); // NOI18N
        jButtonInven1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/IcoInven/Inventario1.png"))); // NOI18N
        jButtonInven1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonInven1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInven1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInven1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 320, 280));

        jPanelMenu.setBackground(new java.awt.Color(119, 187, 255));
        jPanelMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelMenu.setAutoscrolls(true);
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPortal.setBackground(new java.awt.Color(204, 255, 255));
        jLabelPortal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPortal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/portal.jpg"))); // NOI18N
        jPanelMenu.add(jLabelPortal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 160, 140));

        jButtonSalir.setBackground(new java.awt.Color(0, 51, 153));
        jButtonSalir.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/salir.png"))); // NOI18N
        jButtonSalir.setText("        Salir");
        jButtonSalir.setActionCommand("     Salir");
        jButtonSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/salir2.png"))); // NOI18N
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 240, 90));

        jButtonCerrarS.setBackground(new java.awt.Color(0, 51, 153));
        jButtonCerrarS.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButtonCerrarS.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCerrarS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/cerrarSesion.png"))); // NOI18N
        jButtonCerrarS.setText("   Cerra Sesión");
        jButtonCerrarS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonCerrarS.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonCerrarS.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/cerrarSesion2.png"))); // NOI18N
        jButtonCerrarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonCerrarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 240, 90));

        jButtonEditarD.setBackground(new java.awt.Color(0, 51, 153));
        jButtonEditarD.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButtonEditarD.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditarD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/editar.png"))); // NOI18N
        jButtonEditarD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonEditarD.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonEditarD.setLabel("   Editar Datos");
        jButtonEditarD.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/editar2.png"))); // NOI18N
        jButtonEditarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarDActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonEditarD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 240, 90));

        getContentPane().add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, 0, 280, 700));

        jLabelNombrePag.setBackground(new java.awt.Color(0, 51, 204));
        jLabelNombrePag.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelNombrePag.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombrePag.setText("Menú Principal");
        getContentPane().add(jLabelNombrePag, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jButtonMenu1.setBackground(new java.awt.Color(0, 51, 204));
        jButtonMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/menu/menu1.png"))); // NOI18N
        jButtonMenu1.setBorder(null);
        jButtonMenu1.setContentAreaFilled(false);
        jButtonMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMenu1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/menu/menu2.png"))); // NOI18N
        jButtonMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenu1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 90));

        jLabelFondo.setBackground(new java.awt.Color(0, 0, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/fondo.jpg"))); // NOI18N
        jLabelFondo.setText("jLabelFondo");
        jLabelFondo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabelFondo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -40, 1620, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNominaActionPerformed
       JNomina a = new JNomina() ;
       a.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButtonNominaActionPerformed

    private void jButtonContabi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContabi1ActionPerformed
        this.setVisible(false);
        ContPrincipal b = new ContPrincipal();
          b.setSize(700, 500);
        b.setLocation(0,0);
        this.add(b, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
         b.setVisible(true);
         
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonContabi1ActionPerformed

    private void jButtonInven1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInven1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInven1ActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenu1ActionPerformed
        // TODO add your handling code here:
//        int posicion = jButtonMenu1.getX();
//        if (posicion >5 ){
//            Animacion.Animacion
        
        int posicion = jButtonMenu1.getX();
        if(posicion > 5){
            Animacion.Animacion.mover_izquierda(291, 0, 2, 2, jButtonMenu1);
            Animacion.Animacion.mover_izquierda(0, -280, 2, 2, jPanelMenu);
        }else{
            Animacion.Animacion.mover_derecha(0, 290, 2, 2, jButtonMenu1);
            Animacion.Animacion.mover_derecha(-280, 0, 2, 2, jPanelMenu);
        }
        
    }//GEN-LAST:event_jButtonMenu1ActionPerformed

    private void jButtonCerrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSActionPerformed
           
       interfaz a = new interfaz() ;
       a.setVisible(true);
       this.setVisible(false);

    }//GEN-LAST:event_jButtonCerrarSActionPerformed

    private void jButtonEditarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarDActionPerformed

       CambiarD a = new CambiarD();
        a.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButtonEditarDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarS;
    private javax.swing.JButton jButtonContabi1;
    private javax.swing.JButton jButtonEditarD;
    private javax.swing.JButton jButtonInven1;
    private javax.swing.JButton jButtonMenu1;
    private javax.swing.JButton jButtonNomina;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelNombrePag;
    private javax.swing.JLabel jLabelPortal;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables
}
