/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Contabilidad.Beneficiario;
import Contabilidad.Cat1;
import Contabilidad.Contabilidad;
import static interfaz.ContPrincipal.PanelFondo;
import java.awt.BorderLayout;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import interfaz.MostrarBeneficiarios;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MARIAJOSE
 */
public class TercerosOp extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public TercerosOp() {
        initComponents();
    }


    @Override
    public void setVisible(boolean aFlag) {
        super.setVisible(aFlag); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Ter1 = new javax.swing.JRadioButton();
        Ter2 = new javax.swing.JRadioButton();
        Ter3 = new javax.swing.JRadioButton();
        Ter4 = new javax.swing.JRadioButton();
        Aceptar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 255));
        setPreferredSize(new java.awt.Dimension(750, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/icoConta/menuIni/terceros.png"))); // NOI18N
        jLabel1.setText("\n");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setText("TERCEROS");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 344, -1, -1));

        Ter1.setBackground(new java.awt.Color(0, 0, 102));
        buttonGroup1.add(Ter1);
        Ter1.setFont(new java.awt.Font("Times New Roman", 2, 30)); // NOI18N
        Ter1.setText("Añadir tercero");
        add(Ter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 63, -1, -1));

        Ter2.setBackground(new java.awt.Color(0, 0, 102));
        buttonGroup1.add(Ter2);
        Ter2.setFont(new java.awt.Font("Times New Roman", 2, 30)); // NOI18N
        Ter2.setText("Modificar tercero");
        add(Ter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 153, -1, -1));

        Ter3.setBackground(new java.awt.Color(0, 0, 102));
        buttonGroup1.add(Ter3);
        Ter3.setFont(new java.awt.Font("Times New Roman", 2, 30)); // NOI18N
        Ter3.setText("Eliminar tercero");
        add(Ter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 237, -1, -1));

        Ter4.setBackground(new java.awt.Color(0, 0, 102));
        buttonGroup1.add(Ter4);
        Ter4.setFont(new java.awt.Font("Times New Roman", 2, 30)); // NOI18N
        Ter4.setText("Mostrar terceros");
        add(Ter4, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 322, -1, -1));

        Aceptar.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 392, -1, -1));

        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    Cat1 catalogo = new Cat1();
    Contabilidad conta = new Contabilidad(catalogo);
    public boolean leeBene() throws FileNotFoundException, IOException{
        File beneficiarios = new File ("Beneficiarios/beneficiarios.txt");
         FileReader leeBene = new FileReader (beneficiarios);
      BufferedReader bc3 = new BufferedReader  (leeBene);
      String lineaBene;
       while ( (lineaBene = bc3.readLine()) != null){
           String divB[] = lineaBene.split(",");
           String nomB = divB[0];
           String cedBene = divB[1];
           String dirB = divB[2];
           String telB = divB[3];
           Beneficiario ben = new Beneficiario (nomB, cedBene, dirB, telB);
           conta.addBen(ben);
          
       } return true;
    }
    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if (Ter1.isSelected()){ //añadir
            AnadirTerceroPanel pan1 = new AnadirTerceroPanel();
             pan1.setSize(900, 500);
        pan1.setLocation(500, 100);
        PanelFondo.add(pan1, BorderLayout.CENTER);
        PanelFondo.revalidate();
        PanelFondo.repaint();
       
        
          
                         
        } else if (Ter2.isSelected()){ //eliminar
            MofificarPanel pan12 = new MofificarPanel();
             pan12.setSize(900, 500);
        pan12.setLocation(500, 100);
        PanelFondo.add(pan12, BorderLayout.CENTER);
        PanelFondo.revalidate();
        PanelFondo.repaint();
        
        }else if (Ter3.isSelected()){ //modificar
            
        } else if (Ter4.isSelected()){
            try {
                MostrarBeneficiarios.createAndShowGUIBEN();
            } catch (IOException ex) {
                Logger.getLogger(TercerosOp.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_AceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JRadioButton Ter1;
    private javax.swing.JRadioButton Ter2;
    private javax.swing.JRadioButton Ter3;
    private javax.swing.JRadioButton Ter4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
