/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventario;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintStream;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Maicol Velasquez
 */
public class jPanel extends javax.swing.JFrame {

    /**
     * Creates new form jPanel
     */
    
    Inventario in=new Inventario();
    int yt=0;
    
        File Inventario = new File("archIn.txt");
        File plato = new File("archiMa.txt");
    
    public jPanel() {
initComponents();
        

//ArrayList<String> tipos = new ArrayList<String>();
        new Main().leerArch(Inventario, in);
        new Main().leerArchPla(plato, in);
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCrear = new javax.swing.JLabel();
        f = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtoncance = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelTextEli1 = new javax.swing.JLabel();
        jTextFieldIdCrear = new javax.swing.JTextField();
        jButtonBuscEli1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventario - wabisabi");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCrear.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabelCrear.setText(">>Crear plato");
        getContentPane().add(jLabelCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 140, 50));

        f.setBackground(new java.awt.Color(204, 255, 255));
        f.setText(".");
        getContentPane().add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 30, 20));

        jButtonGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGuardarMouseClicked(evt);
            }
        });
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, 110, 30));

        jButtoncance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtoncance.setText("Cancelar");
        jButtoncance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtoncanceMouseClicked(evt);
            }
        });
        jButtoncance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncanceActionPerformed(evt);
            }
        });
        getContentPane().add(jButtoncance, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 110, 30));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(102, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Información del plato:");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Nombre:");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Número de ingredientes");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 230, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 230, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Precio");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 200, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre del ingrediente");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 160, -1));

        jLabel2.setText("Cantidad del ingrediente");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 160, -1));

        jButton2.setText("Guardar ingrediente");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 410, 130));

        jButton4.setText("Agregar ingredientes");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 1030, 300));

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTextEli1.setBackground(new java.awt.Color(0, 153, 255));
        jLabelTextEli1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTextEli1.setText("Escriba nombre del plato:");
        jPanel3.add(jLabelTextEli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTextFieldIdCrear.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldIdCrear.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldIdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdCrearActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldIdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 270, 40));

        jButtonBuscEli1.setBackground(new java.awt.Color(0, 153, 255));
        jButtonBuscEli1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maicol Velasquez\\Documents\\NetBeansProjects\\WabiSabiNomina\\src\\interfaz\\imagenes\\buscar_opt2.png")); // NOI18N
        jButtonBuscEli1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscEli1MouseClicked(evt);
            }
        });
        jButtonBuscEli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscEli1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonBuscEli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 70, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 380, 90));

        jButton1.setText("Regresar");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 500, -1, -1));

        jButton3.setText("Guardar plato");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButtonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarMouseClicked

     
    }//GEN-LAST:event_jButtonGuardarMouseClicked

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtoncanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtoncanceMouseClicked

 
        jTextField4.setText("");
        jTextField5.setText("");
 
        jTextField3.setText("");
      
   
        jTextFieldIdCrear.setText("");
        f.setText("");
    }//GEN-LAST:event_jButtoncanceMouseClicked

    private void jButtoncanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtoncanceActionPerformed

    private void jTextFieldIdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdCrearActionPerformed
        // si el id no exite en array escribe

    }//GEN-LAST:event_jTextFieldIdCrearActionPerformed

    private void jButtonBuscEli1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscEli1MouseClicked
String nomPL=jTextFieldIdCrear.getText();

        for (Platos x : in.getPlatos()) {
            if (jTextFieldIdCrear.getText().equals(x.getNombre())) {

          
             
                jLabel18.setVisible(false);
                jLabel19.setVisible(false);
           
                jLabel20.setVisible(false);
              
                jLabel26.setVisible(false);
                
              

                jTextField4.setVisible(false);
                jTextField5.setVisible(false);
                
                jTextField3.setVisible(false);
                jTextField2.setVisible(false);
                jTextField1.setVisible(false);
                jButtonGuardar.setVisible(false);
                jButton2.setVisible(false);
       jPanel2.setVisible(false);
                //  panel.setVisible(true);
                // this.setVisible(false);
            } else if (!jTextFieldIdCrear.getText().equals(x.getNombre())) {

                jLabel18.setVisible(true);
                jLabel19.setVisible(true);
        
                jLabel20.setVisible(true);
              
                jLabel26.setVisible(true);
            jLabel1.setVisible(false);
            jLabel2.setVisible(false);
               

                jTextField4.setVisible(true);
                jTextField5.setVisible(true);
             
                jTextField3.setVisible(true);
                jTextField1.setVisible(false);
                jTextField2.setVisible(false);
           jPanel2.setVisible(false);
                jButtonGuardar.setVisible(false);
                jButton2.setVisible(false);

            }
        }
    }//GEN-LAST:event_jButtonBuscEli1MouseClicked
    
    private void jButtonBuscEli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscEli1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscEli1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
     
String nombre3="";
                    int can = 0;
                    System.out.println("Ingrese el nombre del plato");
                   String nom = jTextField3.getText();
                   System.out.println("Ingrese el precio del plato");
                   
double precio =  Double.parseDouble(jTextField4.getText());
System.out.println("Ingrese el numero de ingredientes del plato");
int ingrets = Integer.valueOf(jTextField3.getText());
Platos plato1 = new Platos(nom, ingrets, precio);

                if (yt < ingrets ) {
                    System.out.println("Ingrese el nombre de el ingrediente usado");
                    nombre3 = jTextField1.getText();
                    System.out.println("Ingrese la cantidad de: "+nombre3);
                    can = Integer.valueOf(jTextField2.getText());

                    plato1.anadirPla(nombre3, can);
                    yt++;

                }
                
                
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
 try {
String nombre3="";
                    int can = 0;
                    System.out.println("Ingrese el nombre del plato");
                   String nom = jTextField3.getText();
                   System.out.println("Ingrese el precio del plato");
                   
double precio =  Double.parseDouble(jTextField4.getText());
System.out.println("Ingrese el numero de ingredientes del plato");
int ingrets = Integer.valueOf(jTextField3.getText());
Platos plato1 = new Platos(nom, ingrets, precio);
//
//                if (yt < ingrets ) {
//                    System.out.println("Ingrese el nombre de el ingrediente usado");
//                    nombre3 = jTextField1.getText();
//                    System.out.println("Ingrese la cantidad de: "+nombre3);
//                    can = Integer.valueOf(jTextField2.getText());
//
//                    plato1.anadirPla(nombre3, can);
//                    yt++;
//
//                }
                
                if (yt== ingrets){
                in.anadirPla(plato1);
            PrintStream Out7 = new PrintStream(plato);
                new Main().modifPlatos(in, Out7);
                }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(jPanel.class.getName()).log(Level.SEVERE, null, ex);
        }  
        
 
        
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        System.out.println( "AQUI" );
        
        jTextField2.setVisible(true);
                jTextField1.setVisible(true);
                jButtonGuardar.setVisible(true);
                jButton2.setVisible(true);
       jPanel2.setVisible(true); 
 jLabel1.setVisible(true);
            jLabel2.setVisible(true);

String nombre3="";
                    int can = 0;
                    
       String nom = jTextField3.getText();
       int cantidad = Integer.parseInt( jTextField5.getText() );
       double precio =  Double.parseDouble(jTextField4.getText());
       
       System.out.println("Nombre: " + nom );
       System.out.println("Ingrese el precio del plato " + precio );    
       System.out.println("Ingrese el numero de ingredientes del plato " + cantidad );

String cantii = jTextField4.getText();
int ingrets = Integer.parseInt(cantii.trim());
Platos plato1 = new Platos(nom, ingrets, precio);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel f;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonBuscEli1;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtoncance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabelCrear;
    private javax.swing.JLabel jLabelTextEli1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextFieldIdCrear;
    // End of variables declaration//GEN-END:variables
}
